/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StoreDB_CONSTANTS_H
#define StoreDB_CONSTANTS_H

#include "StoreDB_types.h"

namespace storedb {

class StoreDBConstants {
 public:
  StoreDBConstants();

};

extern const StoreDBConstants g_StoreDB_constants;

} // namespace

#endif
